kind = "web"
previewPath = "/"
title = "HypeSpace - Event Management"
version = "1.0.0"
id = "artifacts/hypespace"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19498

[services.development]
run = "pnpm --filter @workspace/hypespace run dev"

[services.env]
PORT = "19498"
BASE_PATH = "/"
